---
- name: Artifactory
  hosts: all
  become: true

  vars:
    - artifactory_database: mysql
    - artifactory_username: artifactory
    - artifactory_password: password
    - mysql_root_password: root

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.mysql
    - role: bbaassssiiee.artifactory
