---
- name: Install Jenkins CI
  hosts: all
  become: true

  vars:
    - jenkins_hostname: localhost
    - jenkins_http_port: 8082
    - jenkins_url_prefix: /jenkins
    - jenkins_admin_username: admin
    - jenkins_admin_password: admin
    - jenkins_package_state: latest
    - jenkins_version: "2.180"

  roles:
    - role: geerlingguy.java
      java_packages:
        - java-1.8.0-openjdk
    - role: geerlingguy.jenkins
