---
- name: Install Jenkins CI
  hosts: all
  become: true

  vars:
    - jenkins_hostname: toolchain.andyneeb.com
    - jenkins_http_port: 80
    - jenkins_url_prefix: /jenkins
    - jenkins_admin_username: admin
    - jenkins_admin_password: Mr!Spock#1

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
