- name: Create user account
  user:
    name: "{{ instance_user }}"

- name: Set Password
  command: "echo {{ instance_password }} | passwd --stdin {{ instance_user }}"
  no_log: True
    
- name: Allow managed user sudo
  lineinfile:
    dest: "/etc/sudoers.d/{{ instance_user }}"
    line: "{{ instance_user }} ALL=(ALL) NOPASSWD: ALL" 
    create: yes 
    state: present
  when: allow_sudo == "True"
